### PR TITLE
remove failure:ignore in .drone.yml

### PR DESCRIPTION
**Pull request by ivan-claire**
Stop ignoring failures on s390x pipelines by removing failure ignores.

### CODE REVIEW

**Review by nikolaishields — APPROVED** [review]

**Review by matttrach — APPROVED** [review]

**Comment by briandowns** [comment]
Conflicts need to be resolved before merging.

**Review by nikolaishields — CHANGES_REQUESTED** [review]
Looks like there's a merge conflict starting on line 64, other than that looks great!

**Comment by matttrach** [comment]
conflicts appear to be trivial, @ivan-claire please review before merge

**Review by briandowns — APPROVED** [review]

**Comment by matttrach** [comment]
Conflicts were trivial again, so I resolved them.

**Review by brandond — CHANGES_REQUESTED** [review]

**Review by brandond — APPROVED** [review]

**Pull request merged**
